#!/bin/bash

orgs=""
sites=""
inspectionDateAfter=""
inspectionDateBefore=""
inspectionId=""

base_url="https://dev-api.axil.ai/airmethane/external/inspections"

url_opts=""

while getopts o:s:a:b:i:l flag
do
    case "${flag}" in
        o) orgs='orgs/'${OPTARG};;
        s) sites='sites/'${OPTARG};;
        a) inspectionDateAfter='inspectionDateAfter/'${OPTARG};;
        b) inspectionDateBefore='inspectionDateBefore/'${OPTARG};;
        i) inspectionId='id/'${OPTARG};;
    esac
done

for ARG in $orgs $sites $inspectionDateAfter $inspectionDateBefore $inspectionId do
  if [ $(expr length "$ARG") > 0 ]; then
    url_opts+='/'"${ARG}"
  fi
done

echo "$base_url""$url_opts"

TOKEN=$(curl --url https://axil.auth0.com/oauth/token --header "Content-Type: application/json" --data \
'{"client_id": "'"$CLIENT_ID"'", "client_secret": "'"$CLIENT_SECRET"'",	"audience": "https://api.axil.ai", "grant_type": "client_credentials"}' | jq -r '.access_token')

curl -X GET \
  --url "$base_url""$url_opts" \
  --header 'Authorization: Bearer '"$TOKEN" >> inspections.json
